// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement = "CggI_00000000"; // <GPGSID>
        public const string achievement350 = "CggI_00000000"; // <GPGSID>
        public const string leaderboard = "CggI_00000000"; // <GPGSID>
        public const string achievement10hands = "CggI_00000000"; // <GPGSID>
        public const string achievement20hands = "CggI_00000000"; // <GPGSID>
        public const string achievement10 = "CggI_00000000"; // <GPGSID>
        public const string achievement200 = "CggI_00000000"; // <GPGSID>
        public const string achievement100 = "CggI_00000000"; // <GPGSID>
        public const string achievement300 = "CggI_00000000"; // <GPGSID>
        public const string achievement15hands = "CggI_00000000"; // <GPGSID>
        public const string achievement250 = "CggI_00000000"; // <GPGSID>
        public const string achievement150 = "CggI_00000000"; // <GPGSID>
        public const string achievement5hands = "CggI_00000000"; // <GPGSID>
        public const string achievement50 = "CggI_00000000"; // <GPGSID>
        public const string achievement25hands = "CggI_00000000"; // <GPGSID>

}

